Add test for branch format on PR merge

diff --git a/.github/workflows/pr-merged.yml b/.github/workflows/pr-merged.yml
--- a/.github/workflows/pr-merged.yml
+++ b/.github/workflows/pr-merged.yml
@@ -4,6 +4,8 @@ on:
     - main
     types: [closed]
 
+name: '[autorelease] PR merged'
+
 jobs:
   merge:
     runs-on: ubuntu-latest
@@ -14,8 +16,11 @@ jobs:
     - name: Get release version
       id: get-release-version
       run: |
-        echo "${{ github.event.pull_request.head.ref }}"
         # Head branch should be named autorelease/<version>
+        if [[ "${{ github.event.pull_request.head.ref }}" =~ ^autorelease\/[A-Za-z0-9.+-]+$ ]]; then
+          echo "Invalid branch"
+          exit 1
+        fi
         VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | awk -F/ '{print $2}')
         echo "VERSION=$VERSION"
         echo "::set-output name=release-version::$VERSION"
@@ -29,6 +34,7 @@ jobs:
     - name: Display release notes
       run: |
         echo "${{ steps.get-release-notes.outputs.release-notes }}"
+
     - name: Create Draft Release
       id: create_release
       uses: actions/create-release@v1
@@ -38,4 +44,4 @@ jobs:
         tag_name: 'v${{ steps.get-release-version.outputs.release-version }}'
         release_name: 'Release ${{ steps.get-release-version.outputs.release-version }}'
         draft: true
-        body: ${{ steps.get-release-version.outputs.release-notes }}
+        body: ${{ steps.get-release-notes.outputs.release-notes }}
