Further regex experiments

diff --git a/.github/workflows/release-published.yml b/.github/workflows/release-published.yml
--- a/.github/workflows/release-published.yml
+++ b/.github/workflows/release-published.yml
@@ -20,14 +20,6 @@ jobs:
     - name: Get release version
       id: get-release-version
       run: |
-        function semverParse() {
-            local RE='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
-            MAJOR=`echo $1 | sed -e "s#$RE#\1#"`
-            MINOR=`echo $1 | sed -e "s#$RE#\2#"`
-            PATCH=`echo $1 | sed -e "s#$RE#\3#"`
-            SPECIAL=`echo $1 | sed -e "s#$RE#\4#"`
-        }
-
         VERSION="${{ github.event.release.tag_name }}"
         if [[ ! $VERSION ]]; then
           VERSION="${{ github.event.inputs.release-version }}"
@@ -35,11 +27,15 @@ jobs:
 
         echo "VERSION=$VERSION"
         
-        RE='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
-        MAJOR=`echo $VERSION | sed -e "s#$RE#\1#"`
-        MINOR=`echo $VERSION | sed -e "s#$RE#\2#"`
-        PATCH=`echo $VERSION | sed -e "s#$RE#\3#"`
-        SPECIAL=`echo $VERSION | sed -e "s#$RE#\4#"`
+        RE='^[vV]?([0-9]+)[.]([0-9]+)[.]([0-9]+)(-[0-9A-Za-z.+-]*)?'
+        if [[ $VERSION =~ $RE ]]; then
+          MAJOR="${BASH_REMATCH[1]}"
+          MINOR="${BASH_REMATCH[2]}"
+          PATCH="${BASH_REMATCH[3]}"
+          SPECIAL="${BASH_REMATCH[4]}"
+        else
+          echo "::error::Version '$VERSION' is not in a valid format" && exit 1
+        fi
 
         echo "MAJOR = $MAJOR"
         if [[ "$SPECIAL" ]]; then
